name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Publish
      run: dotnet publish
    - name: Upload Assets to Release with a wildcard
      uses: csexton/release-asset-action@v2
      with:
       pattern: "ChordPrintCore/bin/Debug/net5.0-windows/publish/*.exe"
       github-token: ${{ secrets.GITHUB_TOKEN }}
       release-url: ${{ steps.create_release.outputs.upload_url }}